# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def ChooseWorkflow(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union[types.Berekening, "types.VerzoekVerduidelijking"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ChooseWorkflow(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="ChooseWorkflow", args={
                "input": input,
            })
            return typing.cast(typing.Union[types.Berekening, "types.VerzoekVerduidelijking"], result.cast_to(types, types, stream_types, False, __runtime__))
    async def ClassifyWork(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union[types.TypeOfWork, "types.ClarificationRequest"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ClassifyWork(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyWork", args={
                "input": input,
            })
            return typing.cast(typing.Union[types.TypeOfWork, "types.ClarificationRequest"], result.cast_to(types, types, stream_types, False, __runtime__))
    async def DetermineNextStep(self, thread: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.AddTool", "types.SubtractTool", "types.MultiplyTool", "types.DivideTool", "types.ClarificationRequest", "types.DoneForNow"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.DetermineNextStep(thread=thread,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="DetermineNextStep", args={
                "thread": thread,
            })
            return typing.cast(typing.Union["types.AddTool", "types.SubtractTool", "types.MultiplyTool", "types.DivideTool", "types.ClarificationRequest", "types.DoneForNow"], result.cast_to(types, types, stream_types, False, __runtime__))
    async def FoundationDesignAssumptionsReporter(self, input: types.ReportBaseLineAssumptions,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.FoundationDesignAssumptionsReporter(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="FoundationDesignAssumptionsReporter", args={
                "input": input,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def FoundationDesignConclusionReporter(self, input: types.ReportBaseLineConclusion,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.FoundationDesignConclusionReporter(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="FoundationDesignConclusionReporter", args={
                "input": input,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def FoundationDesignIntroductionReporter(self, input: types.ReportBaseLineIntroduction,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.FoundationDesignIntroductionReporter(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="FoundationDesignIntroductionReporter", args={
                "input": input,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def FoundationDesignModellingReporter(self, input: types.ReportBaseLineModelling,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.FoundationDesignModellingReporter(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="FoundationDesignModellingReporter", args={
                "input": input,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def FoundationDesignResultsReporter(self, input: types.ReportBaseResults,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.FoundationDesignResultsReporter(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="FoundationDesignResultsReporter", args={
                "input": input,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def FoundationDesignSoilInvestigationReporter(self, input: types.ReportBaseLineSoilInvestigation,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.FoundationDesignSoilInvestigationReporter(input=input,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="FoundationDesignSoilInvestigationReporter", args={
                "input": input,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseWorkflow(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union[types.Berekening, "stream_types.VerzoekVerduidelijking"], typing.Union[types.Berekening, "types.VerzoekVerduidelijking"]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ChooseWorkflow", args={
            "input": input,
        })
        return baml_py.BamlStream[typing.Union[types.Berekening, "stream_types.VerzoekVerduidelijking"], typing.Union[types.Berekening, "types.VerzoekVerduidelijking"]](
          result,
          lambda x: typing.cast(typing.Union[types.Berekening, "stream_types.VerzoekVerduidelijking"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union[types.Berekening, "types.VerzoekVerduidelijking"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ClassifyWork(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union[types.TypeOfWork, "stream_types.ClarificationRequest"], typing.Union[types.TypeOfWork, "types.ClarificationRequest"]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyWork", args={
            "input": input,
        })
        return baml_py.BamlStream[typing.Union[types.TypeOfWork, "stream_types.ClarificationRequest"], typing.Union[types.TypeOfWork, "types.ClarificationRequest"]](
          result,
          lambda x: typing.cast(typing.Union[types.TypeOfWork, "stream_types.ClarificationRequest"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union[types.TypeOfWork, "types.ClarificationRequest"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def DetermineNextStep(self, thread: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.AddTool", "stream_types.SubtractTool", "stream_types.MultiplyTool", "stream_types.DivideTool", "stream_types.ClarificationRequest", "stream_types.DoneForNow"], typing.Union["types.AddTool", "types.SubtractTool", "types.MultiplyTool", "types.DivideTool", "types.ClarificationRequest", "types.DoneForNow"]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="DetermineNextStep", args={
            "thread": thread,
        })
        return baml_py.BamlStream[typing.Union["stream_types.AddTool", "stream_types.SubtractTool", "stream_types.MultiplyTool", "stream_types.DivideTool", "stream_types.ClarificationRequest", "stream_types.DoneForNow"], typing.Union["types.AddTool", "types.SubtractTool", "types.MultiplyTool", "types.DivideTool", "types.ClarificationRequest", "types.DoneForNow"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.AddTool", "stream_types.SubtractTool", "stream_types.MultiplyTool", "stream_types.DivideTool", "stream_types.ClarificationRequest", "stream_types.DoneForNow"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.AddTool", "types.SubtractTool", "types.MultiplyTool", "types.DivideTool", "types.ClarificationRequest", "types.DoneForNow"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FoundationDesignAssumptionsReporter(self, input: types.ReportBaseLineAssumptions,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FoundationDesignAssumptionsReporter", args={
            "input": input,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FoundationDesignConclusionReporter(self, input: types.ReportBaseLineConclusion,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FoundationDesignConclusionReporter", args={
            "input": input,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FoundationDesignIntroductionReporter(self, input: types.ReportBaseLineIntroduction,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FoundationDesignIntroductionReporter", args={
            "input": input,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FoundationDesignModellingReporter(self, input: types.ReportBaseLineModelling,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FoundationDesignModellingReporter", args={
            "input": input,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FoundationDesignResultsReporter(self, input: types.ReportBaseResults,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FoundationDesignResultsReporter", args={
            "input": input,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FoundationDesignSoilInvestigationReporter(self, input: types.ReportBaseLineSoilInvestigation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FoundationDesignSoilInvestigationReporter", args={
            "input": input,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChooseWorkflow(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseWorkflow", args={
            "input": input,
        }, mode="request")
        return result
    async def ClassifyWork(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyWork", args={
            "input": input,
        }, mode="request")
        return result
    async def DetermineNextStep(self, thread: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetermineNextStep", args={
            "thread": thread,
        }, mode="request")
        return result
    async def FoundationDesignAssumptionsReporter(self, input: types.ReportBaseLineAssumptions,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignAssumptionsReporter", args={
            "input": input,
        }, mode="request")
        return result
    async def FoundationDesignConclusionReporter(self, input: types.ReportBaseLineConclusion,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignConclusionReporter", args={
            "input": input,
        }, mode="request")
        return result
    async def FoundationDesignIntroductionReporter(self, input: types.ReportBaseLineIntroduction,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignIntroductionReporter", args={
            "input": input,
        }, mode="request")
        return result
    async def FoundationDesignModellingReporter(self, input: types.ReportBaseLineModelling,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignModellingReporter", args={
            "input": input,
        }, mode="request")
        return result
    async def FoundationDesignResultsReporter(self, input: types.ReportBaseResults,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignResultsReporter", args={
            "input": input,
        }, mode="request")
        return result
    async def FoundationDesignSoilInvestigationReporter(self, input: types.ReportBaseLineSoilInvestigation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignSoilInvestigationReporter", args={
            "input": input,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChooseWorkflow(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChooseWorkflow", args={
            "input": input,
        }, mode="stream")
        return result
    async def ClassifyWork(self, input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyWork", args={
            "input": input,
        }, mode="stream")
        return result
    async def DetermineNextStep(self, thread: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetermineNextStep", args={
            "thread": thread,
        }, mode="stream")
        return result
    async def FoundationDesignAssumptionsReporter(self, input: types.ReportBaseLineAssumptions,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignAssumptionsReporter", args={
            "input": input,
        }, mode="stream")
        return result
    async def FoundationDesignConclusionReporter(self, input: types.ReportBaseLineConclusion,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignConclusionReporter", args={
            "input": input,
        }, mode="stream")
        return result
    async def FoundationDesignIntroductionReporter(self, input: types.ReportBaseLineIntroduction,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignIntroductionReporter", args={
            "input": input,
        }, mode="stream")
        return result
    async def FoundationDesignModellingReporter(self, input: types.ReportBaseLineModelling,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignModellingReporter", args={
            "input": input,
        }, mode="stream")
        return result
    async def FoundationDesignResultsReporter(self, input: types.ReportBaseResults,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignResultsReporter", args={
            "input": input,
        }, mode="stream")
        return result
    async def FoundationDesignSoilInvestigationReporter(self, input: types.ReportBaseLineSoilInvestigation,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FoundationDesignSoilInvestigationReporter", args={
            "input": input,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))