# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseWorkflow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union[types.Berekening, "types.VerzoekVerduidelijking"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseWorkflow", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union[types.Berekening, "types.VerzoekVerduidelijking"], result)

    def ClassifyWork(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union[types.TypeOfWork, "types.ClarificationRequest"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyWork", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union[types.TypeOfWork, "types.ClarificationRequest"], result)

    def DetermineNextStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.AddTool", "types.SubtractTool", "types.MultiplyTool", "types.DivideTool", "types.ClarificationRequest", "types.DoneForNow"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetermineNextStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.AddTool", "types.SubtractTool", "types.MultiplyTool", "types.DivideTool", "types.ClarificationRequest", "types.DoneForNow"], result)

    def FoundationDesignAssumptionsReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignAssumptionsReporter", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def FoundationDesignConclusionReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignConclusionReporter", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def FoundationDesignIntroductionReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignIntroductionReporter", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def FoundationDesignModellingReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignModellingReporter", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def FoundationDesignResultsReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignResultsReporter", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def FoundationDesignSoilInvestigationReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignSoilInvestigationReporter", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def RerankCandidates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RerankedMatch"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RerankCandidates", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.RerankedMatch"], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChooseWorkflow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union[types.Berekening, "stream_types.VerzoekVerduidelijking"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ChooseWorkflow", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union[types.Berekening, "stream_types.VerzoekVerduidelijking"], result)

    def ClassifyWork(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union[types.TypeOfWork, "stream_types.ClarificationRequest"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyWork", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union[types.TypeOfWork, "stream_types.ClarificationRequest"], result)

    def DetermineNextStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.AddTool", "stream_types.SubtractTool", "stream_types.MultiplyTool", "stream_types.DivideTool", "stream_types.ClarificationRequest", "stream_types.DoneForNow"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetermineNextStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.AddTool", "stream_types.SubtractTool", "stream_types.MultiplyTool", "stream_types.DivideTool", "stream_types.ClarificationRequest", "stream_types.DoneForNow"], result)

    def FoundationDesignAssumptionsReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignAssumptionsReporter", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def FoundationDesignConclusionReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignConclusionReporter", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def FoundationDesignIntroductionReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignIntroductionReporter", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def FoundationDesignModellingReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignModellingReporter", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def FoundationDesignResultsReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignResultsReporter", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def FoundationDesignSoilInvestigationReporter(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FoundationDesignSoilInvestigationReporter", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def RerankCandidates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.RerankedMatch"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RerankCandidates", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.RerankedMatch"], result)

    