# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (16)
# #########################################################################

class AddTool(BaseModel):
    intent: typing.Optional[str] = None
    a: typing.Optional[typing.Union[int, float]] = None
    b: typing.Optional[typing.Union[int, float]] = None

class ClarificationRequest(BaseModel):
    intent: typing.Optional[str] = None
    message: typing.Optional[str] = None

class DivideTool(BaseModel):
    intent: typing.Optional[str] = None
    a: typing.Optional[typing.Union[int, float]] = None
    b: typing.Optional[typing.Union[int, float]] = None

class DoneForNow(BaseModel):
    intent: typing.Optional[str] = None
    message: typing.Optional[str] = None

class ModellingPointers(BaseModel):
    soil_profiles: typing.List[str]
    pile: typing.List[str]
    variability_information: typing.List[str]
    environmental_factors: typing.List[str]

class MultiplyTool(BaseModel):
    intent: typing.Optional[str] = None
    a: typing.Optional[typing.Union[int, float]] = None
    b: typing.Optional[typing.Union[int, float]] = None

class ReportBaseLineAssumptions(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]
    parameters: typing.List[typing.Dict[str, typing.Union[float, bool, str]]]

class ReportBaseLineConclusion(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ReportBaseLineIntroduction(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ReportBaseLineModelling(BaseModel):
    pointers: typing.Optional["ModellingPointers"] = None
    elements: typing.List["ReportElement"]

class ReportBaseLineSoilInvestigation(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ReportBaseResults(BaseModel):
    pointers: typing.Optional["ResultPointers"] = None
    elements: typing.List["ReportElement"]

class ReportElement(BaseModel):
    element: typing.Optional[str] = None
    description: typing.Optional[str] = None

class ResultPointers(BaseModel):
    pile_tip_range: typing.Optional[str] = None
    bearing_capacity: typing.Optional[str] = None
    load: typing.Optional[str] = None
    pile_tip_level: typing.Optional[str] = None

class SubtractTool(BaseModel):
    intent: typing.Optional[str] = None
    a: typing.Optional[typing.Union[int, float]] = None
    b: typing.Optional[typing.Union[int, float]] = None

class VerzoekVerduidelijking(BaseModel):
    intentie: typing.Optional[str] = None
    verzoek_tot_verduidelijking: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (2)
# #########################################################################


CalculatorTools: typing_extensions.TypeAlias = typing.Optional[typing.Union["AddTool", "SubtractTool", "MultiplyTool", "DivideTool"]]


HumanTools: typing_extensions.TypeAlias = typing.Optional[typing.Union["ClarificationRequest", "DoneForNow"]]
