# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AddTool": types.AddTool,
    "stream_types.AddTool": stream_types.AddTool,

    "types.ClarificationRequest": types.ClarificationRequest,
    "stream_types.ClarificationRequest": stream_types.ClarificationRequest,

    "types.DivideTool": types.DivideTool,
    "stream_types.DivideTool": stream_types.DivideTool,

    "types.DoneForNow": types.DoneForNow,
    "stream_types.DoneForNow": stream_types.DoneForNow,

    "types.ModellingPointers": types.ModellingPointers,
    "stream_types.ModellingPointers": stream_types.ModellingPointers,

    "types.MultiplyTool": types.MultiplyTool,
    "stream_types.MultiplyTool": stream_types.MultiplyTool,

    "types.ReportBaseLineAssumptions": types.ReportBaseLineAssumptions,
    "stream_types.ReportBaseLineAssumptions": stream_types.ReportBaseLineAssumptions,

    "types.ReportBaseLineConclusion": types.ReportBaseLineConclusion,
    "stream_types.ReportBaseLineConclusion": stream_types.ReportBaseLineConclusion,

    "types.ReportBaseLineIntroduction": types.ReportBaseLineIntroduction,
    "stream_types.ReportBaseLineIntroduction": stream_types.ReportBaseLineIntroduction,

    "types.ReportBaseLineModelling": types.ReportBaseLineModelling,
    "stream_types.ReportBaseLineModelling": stream_types.ReportBaseLineModelling,

    "types.ReportBaseLineSoilInvestigation": types.ReportBaseLineSoilInvestigation,
    "stream_types.ReportBaseLineSoilInvestigation": stream_types.ReportBaseLineSoilInvestigation,

    "types.ReportBaseResults": types.ReportBaseResults,
    "stream_types.ReportBaseResults": stream_types.ReportBaseResults,

    "types.ReportElement": types.ReportElement,
    "stream_types.ReportElement": stream_types.ReportElement,

    "types.ResultPointers": types.ResultPointers,
    "stream_types.ResultPointers": stream_types.ResultPointers,

    "types.SubtractTool": types.SubtractTool,
    "stream_types.SubtractTool": stream_types.SubtractTool,

    "types.VerzoekVerduidelijking": types.VerzoekVerduidelijking,
    "stream_types.VerzoekVerduidelijking": stream_types.VerzoekVerduidelijking,


    "types.Berekening": types.Berekening,

    "types.TypeOfWork": types.TypeOfWork,

}