# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class Berekening(str, Enum):
    PAALFUNDERING = "PAALFUNDERING"
    STABILITEIT = "STABILITEIT"
    ZETTINGEN = "ZETTINGEN"
    DAMWAND = "DAMWAND"

class TypeOfWork(str, Enum):
    INTERPRET_SOIL_INVESTIGATION = "INTERPRET_SOIL_INVESTIGATION"
    DERIVE_SOIL_PARAMETERS = "DERIVE_SOIL_PARAMETERS"
    CALCULATE = "CALCULATE"
    REPORT = "REPORT"

# #########################################################################
# Generated classes (16)
# #########################################################################

class AddTool(BaseModel):
    intent: typing_extensions.Literal['add']
    a: typing.Union[int, float]
    b: typing.Union[int, float]

class ClarificationRequest(BaseModel):
    intent: typing_extensions.Literal['request_more_information']
    message: str

class DivideTool(BaseModel):
    intent: typing_extensions.Literal['divide']
    a: typing.Union[int, float]
    b: typing.Union[int, float]

class DoneForNow(BaseModel):
    intent: typing_extensions.Literal['done_for_now']
    message: str

class ModellingPointers(BaseModel):
    soil_profiles: typing.List[str]
    pile: typing.List[str]
    variability_information: typing.List[str]
    environmental_factors: typing.List[str]

class MultiplyTool(BaseModel):
    intent: typing_extensions.Literal['multiply']
    a: typing.Union[int, float]
    b: typing.Union[int, float]

class ReportBaseLineAssumptions(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]
    parameters: typing.List[typing.Dict[str, typing.Union[float, bool, str]]]

class ReportBaseLineConclusion(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ReportBaseLineIntroduction(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ReportBaseLineModelling(BaseModel):
    pointers: "ModellingPointers"
    elements: typing.List["ReportElement"]

class ReportBaseLineSoilInvestigation(BaseModel):
    pointers: typing.List[str]
    elements: typing.List["ReportElement"]

class ReportBaseResults(BaseModel):
    pointers: "ResultPointers"
    elements: typing.List["ReportElement"]

class ReportElement(BaseModel):
    element: str
    description: str

class ResultPointers(BaseModel):
    pile_tip_range: str
    bearing_capacity: str
    load: str
    pile_tip_level: str

class SubtractTool(BaseModel):
    intent: typing_extensions.Literal['subtract']
    a: typing.Union[int, float]
    b: typing.Union[int, float]

class VerzoekVerduidelijking(BaseModel):
    intentie: typing_extensions.Literal['Geef meer informatie']
    verzoek_tot_verduidelijking: str

# #########################################################################
# Generated type aliases (2)
# #########################################################################


CalculatorTools: typing_extensions.TypeAlias = typing.Union["AddTool", "SubtractTool", "MultiplyTool", "DivideTool"]


HumanTools: typing_extensions.TypeAlias = typing.Union["ClarificationRequest", "DoneForNow"]
